/**
 * ask-coverage.fixtures.ts — ivy-t's September 2026, verbatim: the brief's ten undated asks and
 * the thirty-three posts the month generated from them.
 *
 * Prod cycle d71da70e, read on 2026-09-01 and never written to. VERBATIM, for the reason the
 * caption-overlap fixtures are: the whole point is the verdict, and a paraphrased corpus would
 * exercise the arithmetic while proving nothing about the thresholds the arithmetic exists to
 * apply.
 *
 * The corpus is COMPLETE — every live post, every caption in full. That completeness is load
 * bearing rather than thorough: an `unused` verdict is a claim that words appear NOWHERE in the
 * month, and a trimmed corpus would make every such verdict unsound while still passing.
 *
 * This is Sprigly's own generated output for a client, not a client record: no contact, no
 * commercial term, no correspondence. The four hooks are the client's own words, kept because
 * they are the thing that went missing.
 */

/** The ten content_asks exactly as `structured_brief` holds them. */
export const SEPT_ASKS = [
  { type: 'customer-message-hook', product: null,
    note: 'Hook: A customer just sent me this message…. Use as a hook post.' },
  { type: 'wardrobe-avoidance-hook', product: null,
    note: 'Hook: Do you avoid sorting your wardrobe out?' },
  { type: 'shop-your-wardrobe-hook', product: null,
    note: 'Hook: Do you avoid shopping your own wardrobe?' },
  { type: 'reach-for-same-clothes-hook', product: null,
    note: 'Hook: Do you always reach for the same clothes?' },
  { type: 'named-after-women-brand-story', product: null,
    note: 'All named after girls and women in our lives, these girls become familiar friends to you. There to make you feel good, to rely on and to help you bring your best, just like a true friend.' },
  { type: 'cost-per-wear-education', product: 'Audrey',
    note: '£50 for a long sleeve t-shirt — talk through the reasons for the cost and why it is worth spending: fit better, wash better, wear better, last longer. Women commenting on our ads saying £50 is expensive. We get that it\'s not for everyone — and that\'s okay. But here is why more and more women understand that investing in their clothes makes sense long term. Wear this top just twice a week for two years and it costs around 24p per wear (less in real life as you\'ll have it for more than 2 years). That\'s less than a coffee, a bottle of water, a can of fizzy drink, a chocolate bar, or a packet of crisps. Those purchases are gone in minutes. This is a wardrobe staple you\'ll keep reaching for hundreds of times. Cheap clothing always comes at a cost — if not to the customer, then often to the people making it or to the planet.' },
  { type: 'not-fast-fashion-brand-values', product: null,
    note: 'We don\'t compete with fast fashion because we don\'t make fast fashion. We are in our own lane. Every piece is produced in small batches using consciously sourced fabrics and ethical manufacturing. We choose quality over quantity, pay fairly, reduce waste, and create garments designed to be worn for years, not weeks. We\'d rather make fewer pieces, make them properly, and stand behind every one of them. If that\'s the kind of fashion you\'re looking for, you\'re exactly who we make them for. 💛' },
  { type: 'organic-cotton-sensitive-skin-education', product: null,
    note: 'What makes organic cotton the only choice for sensitive skin.' },
  { type: 'navy-edit-customer-reaction', product: 'Navy Edit',
    note: 'Talk about the Navy Edit that launched at the end of August and what customers are starting to say about it.' },
  { type: 'what-i-am-most-proud-of-series', product: null,
    note: 'Add a new post in the \'What I am most proud of….\' series sharing one specific aspect of brand/styles/fabrics/team/who has worn our clothes, and even more personal things about Sally, e.g. the daily juggle. Examples include the quality and washability of our clothes, the longevity of our range meaning they can be cherished for many seasons, the certification of our organic cotton, and giving women the simplicity of getting dressed. Can pull various ideas from https://ivyt.co.uk/pages/our-story-new and https://ivyt.co.uk/pages/our-founder' },
] as const;

/** The full structured_brief shape the detector reads (only content_asks is consulted). */
export const SEPT_BRIEF = { content_asks: SEPT_ASKS as unknown as Array<Record<string, unknown>> };

/** All 33 live posts: title, caption, hook, script, overlay. `notes` is omitted — the detector
 *  does not read it, and including it would invite a future edit to start counting the steer
 *  as the outcome. */
export const SEPT_POSTS = [
  { title: 'September opener — Navy Edit customer reaction',
    caption: 'The Navy Edit in Navy landed at the end of August, and your messages have been coming in ever since.\n\nWe won\'t name names, but one note in particular made us stop mid-morning and read it out loud. Women telling us they\'ve finally found the navy they\'ve been searching for. That it sits differently. That they put it on and just felt right.\n\nThis is exactly why we make what we make. Not to fill a gap in the market, but to fill a gap in your wardrobe. The one you didn\'t know was there until you found the piece that fits it perfectly.\n\nThe Navy Edit in Navy is in the link in our bio. We\'d love to know what you think once she\'s yours. 🤍',
    hook: '', script: '', overlay: '' },
  { title: 'Jen Was Made for This',
    caption: 'Can I tell you why Jen exists?\n\nI spent years searching for a sweatshirt that wasn\'t a fashion piece. Not oversized for the sake of it, not covered in branding, not made from something that would bobble and pill after a few washes. Just a good, well-made half-zip in organic cotton that you could throw on and actually rely on.\n\nI couldn\'t find one I trusted. So we made one.\n\nThe Jen Navy Half Zip Sweatshirt is GOTS-certified organic cotton jersey, cut with a clean, easy fit that works as hard as you need it to. She\'s the kind of piece you stop noticing in the best possible way, she\'s just always there, always right, always effortless.\n\nThat\'s the entire point of Ivy. Not to fill your wardrobe, but to solve the gaps in it.\n\nLove, Sally x',
    hook: 'For years, I searched for a sweatshirt I could actually trust. I never found one.', script: 'HOOK: For years, I searched for a sweatshirt I could actually trust. I never found one.\n\nBEAT 1 (0–12s) — Not oversized for the sake of it, not covered in branding, not made from something that pills after a few washes — just a clean half-zip in GOTS-certified organic cotton that you could reach for on repeat. (Sally to camera, direct)\n\nBEAT 2 (12–22s) — So we made her. Jen is that piece: she\'s always there, always right, never asks anything of you. (slow garment detail close-up, then Sally holding Jen up)\n\nCTA: I\'d love to know what you think. 🤍', overlay: '' },
  { title: 'Named after women — brand story',
    caption: 'Every piece we make is named after a girl or woman in our lives. 🤍\n\nAudrey. Hannah. Claire. Mabel. Emma. Connie. Each one named with intention, each one carrying a little piece of someone real.\n\nOver time, something shifts. These names stop being product names and start feeling familiar. Reliable. The ones you reach for on the hard mornings as much as the good ones.\n\nThese girls become friends. That\'s the idea, and always has been.',
    hook: '', script: '', overlay: '' },
  { title: 'Maya, Close to Home',
    caption: 'Every piece in our range is named after a girl or woman in my life. 🤍\n\nSisters, friends, daughters, mothers. Women who have shown up, made me laugh, held things together on the hard days.\n\nMaya is one of those women. She knows who she is. And every time I see her name on the label, I feel it.\n\nThat is what this brand has always been about for me. Not just the clothes, but the people behind them. The women who shaped everything.\n\nIf you have ever wondered why we name our pieces the way we do, this is why.\n\nLove, Sally x',
    hook: 'Everything changed when I realised the names on our labels weren\'t just names.', script: 'HOOK: Everything changed when I realised the names on our labels weren\'t just names.\n\nBEAT 1 (0–12s) — Every piece is named after a real woman in my life. Sisters, friends, daughters. Women who showed up on the hard days. (Sally to camera, warm and direct)\n\nBEAT 2 (12–24s) — Maya is one of those women. Every time I see her name on a label, I feel it. (Close-up of a label reading "Maya", then back to Sally\'s face)\n\nCTA: I\'d love to know if that changes how you think about the clothes you wear.', overlay: '' },
  { title: 'WSG — Navy Edit weekend outfit',
    caption: '✨ Weekend Style Guide ✨\n\nI\'ve been reaching for the Navy Edit more than anything else this week, and I wanted to show you exactly how I\'ve been wearing her.\n\nThere\'s something about a proper navy that just settles an outfit. Not dark enough to be heavy, not light enough to be casual. She sits right in the middle of everything, which means she goes with everything too.\n\nThis week I\'ve had her on with a Claire skirt in the morning, with my Kate Joggers in Grey Marl for the school run, and honestly, on her own tucked in on Thursday evening when I couldn\'t face a decision.\n\nThe Navy Edit in Navy. She\'s a good one.\n\nHave a wonderful weekend. Love, Sally 😘',
    hook: '', script: '', overlay: '' },
  { title: 'The Quiet Strength of Good Foundations',
    caption: 'The pieces you never have to think about are doing the most work.\n\nNot the statement buy. Not the occasion dress. The everyday foundation, the T-Shirt that fits properly, washes without losing its shape, and sits easily next to everything else you own. The piece you reach for on autopilot and never regret.\n\nThat\'s what we set out to build at Ivy. Not a full wardrobe, not a new trend every season, just the pieces that make every other piece work better. When your foundations are right, getting dressed stops being a decision and starts being easy.\n\nWe call them stable foundations for a reason. They hold everything else up. 🤍',
    hook: 'When did you last reach for something without thinking — and realise it was doing all the work?', script: 'HOOK: When did you last reach for something without thinking — and realise it was doing all the work?\n\nBEAT 1 (0–10s) — That\'s a foundation piece. Not the statement buy, not the occasion dress — the T-shirt that fits properly, washes without losing its shape, and sits easily next to everything else you own. (Sally to camera, relaxed)\n\nBEAT 2 (10–22s) — At Ivy, that\'s all we set out to build. When your foundations are right, getting dressed stops being a decision and starts being easy. (flat-lay of folded basics, unhurried)\n\nCTA: Our DMs are always open and we love hearing from you. 🤍', overlay: '' },
  { title: 'Made for the Way You Live',
    caption: 'Clothes that move with you, not against you. 🤍\n\nThat\'s the entire idea behind everything we make at Ivy. Not pieces that look perfect on a hanger and feel awkward the moment you put them on. Pieces that work for the school run and the school pick-up, the desk and the dinner, the days when you want to feel pulled together without spending a single second thinking about it.\n\nEvery fit we develop starts with a simple question: does this work for how women actually live? Not how we wish they lived, or how a fit model lives. How you live. That means a shoulder seam that sits right when you\'re carrying a bag, a hem length that works whether you\'re sitting or standing, and organic cotton jersey that breathes and moves because it\'s knitted, not stiff.\n\nEach piece is named after a woman in our lives, because that\'s exactly who we make them for. Women who are busy, capable, and deserve to get dressed without it being a whole thing.\n\nWe\'d love to know which piece has made your mornings that little bit easier. Come and tell us in the comments 👇',
    hook: 'Stop dressing for the hanger. Dress for how you actually live.', script: '', overlay: '' },
  { title: 'Notes from the Founder: Meet Fiona',
    caption: 'Can I tell you about Fiona? 🤍\n\nEvery piece we make is named after a woman in our lives, and Fiona is no different. She\'s the friend who turns up. The one you can call on, the one who makes you feel steadier just by being there. That\'s exactly what I wanted her sweatshirt dress to do for you.\n\nFiona, our sweatshirt dress in Slate, is the kind of piece you put on when you want to feel pulled together without thinking too hard about it. Soft organic cotton, a relaxed fit that moves with you, and a colour that works with everything else already hanging in your wardrobe. She\'s the friend who makes your other clothes better.\n\nI named her after someone who does exactly that for me. And I hope she does the same for you.\n\nMuch love, Sally x',
    hook: 'If you want to feel pulled together without thinking about it, this one\'s for you.', script: 'HOOK: If you want to feel pulled together without thinking about it, this one\'s for you.\n\nBEAT 1 (0–10s) — This is Fiona, our sweatshirt dress in Slate, and she\'s named after a friend who always shows up — because that\'s exactly what I wanted her to do for you. (Sally to camera, holding Fiona up)\n\nBEAT 2 (10–22s) — Soft GOTS-certified organic cotton, a relaxed fit that moves with you, and a colour that works with everything already in your wardrobe — because a piece that goes with nothing isn\'t a wardrobe staple, it\'s a problem. (garment detail close-up, fabric drape)\n\nCTA: Comment \'Fiona\' to join the waitlist. 🤍', overlay: '' },
  { title: 'Built Because Something Was Missing',
    caption: 'Ivy exists because I couldn\'t find what I needed anywhere else.\n\nI was working in fashion. I knew exactly how clothes were made, where corners got cut, and why so many basics felt disappointing the moment you got them home. The fit was off. The fabric softened in the wrong way after a few washes. The colour crept. The seams twisted.\n\nI wasn\'t looking for anything complicated. I just wanted a really good T-Shirt. One made properly, in organic cotton, that felt as good on day forty as it did on day one. One that worked with everything in my wardrobe without me having to think about it.\n\nI couldn\'t find her. So I made her.\n\nThat\'s still the whole reason Ivy exists. Not to follow trends. Not to fill space in your wardrobe with pieces you\'ll wear twice and forget. To make fewer things, make them properly, and give you the kind of basics that quietly hold your whole wardrobe together.\n\nEvery piece is named after a woman in my life. Every one is made to earn a place in yours.\n\nIf you\'re new here, welcome. Our DMs are always open and we love hearing from you 🫶\n\nLove, Sally x',
    hook: 'We\'re not a trend-led clothing brand. Here\'s what we actually are.', script: '', overlay: '' },
  { title: 'Ethical Isn\'t a Compromise',
    caption: 'Sustainable doesn\'t mean settling for less. 🤍\n\nWe hear it sometimes: why pay more for a T-Shirt? The honest answer is that everything in our range is made properly, or it doesn\'t get made at all. That means GOTS-certified organic cotton, a Portuguese factory that pays fair wages and runs on solar power, and small batches that reduce waste from the start.\n\nWe don\'t cut corners to hit a lower price point. We don\'t add polyester to make the fabric cheaper to produce. We don\'t rush a fit to get a garment out faster. Every one of those decisions would cost something, and that cost would land somewhere, whether on the women making our clothes, on the planet, or eventually on you when the garment doesn\'t last.\n\nQuality and ethics aren\'t competing priorities at Ivy. They are the same thing. Made right, worn often, loved longer. 💛',
    hook: 'We were told to add a little polyester to keep prices down. We said no every time.', script: 'HOOK: We were told to add a little polyester to keep prices down. We said no every time. (Sally to camera, direct eye contact)\n\nBEAT 1 (0–8s) — Polyester makes fabric cheaper to produce, but it pills faster, it doesn\'t breathe, and that cost lands on you when the garment doesn\'t last. (close-up of GOTS-certified organic cotton fabric, texture visible)\n\nBEAT 2 (8–20s) — Everything we make is GOTS-certified organic cotton, cut in small batches, in a Portuguese factory that pays fair wages and runs on solar power, because quality and ethics are the same decision. (flat-lay of folded garments, clean and simple)\n\nCTA: Our DMs are always open if you\'d like to know more. 🤍', overlay: '' },
  { title: 'The People Behind What We Make',
    caption: 'Every piece of Ivy clothing passes through a lot of hands before it reaches yours. 🤍\n\nOur factory in Portugal is a place we are genuinely proud of. It is Sedex-approved, pays fair wages, and runs on solar power. The people there have been making clothes for decades. They know when something is right and they are not afraid to tell us when it isn\'t. That honesty is part of why our fit is what it is.\n\nBack here, there is a small team that answers every DM, thinks about every size question, and genuinely wants to get it right for you. When you ask us something, a real person reads it and a real person replies.\n\nWe think that matters. Not because it is a selling point, but because it is just how we think things should work.\n\nOur DMs are always open and we love hearing from you 🫶',
    hook: 'If you only remember one thing about building a wardrobe you actually reach for, make it this.', script: '', overlay: '' },
  { title: 'WSG: Your Weekend, Simplified With Jane',
    caption: '✨ Weekend Style Guide ✨\n\nSome Saturdays I just want to reach for one thing and be done with it.\n\nThis week that thing is Jane in Black. She is the simplest V-neck tee I own, and somehow that simplicity is the whole point. No fuss, no overthinking, no standing in front of the wardrobe wondering what goes with what. She just works.\n\nI\'ve had her on since this morning with wide-leg linen trousers and flat sandals, and I\'ll still be wearing her tonight with a good pair of jeans and something to keep the chill off. Two completely different looks, zero effort between them.\n\nThat\'s the kind of getting-dressed day I want every weekend. Simple. Sorted. Done.\n\nHave a lovely weekend, love, Sally 😘',
    hook: 'Have you ever stood in front of a full wardrobe and still not known what to wear?', script: '', overlay: '' },
  { title: 'Start With Something That Lasts',
    caption: 'Start with something that lasts. 🤍\n\nThe pieces that earn their place in your wardrobe aren\'t the ones you wear once and forget. They\'re the ones you reach for on repeat, season after season, without ever stopping to think twice.\n\nThat\'s what we built Ivy around. Not more options, not faster refreshes, just fewer, better pieces that genuinely hold their shape, their colour, and their softness wash after wash. GOTS-certified organic cotton jersey doesn\'t pill, doesn\'t twist, and doesn\'t go thin at the seams after six months. It stays the way it looked the first time you put it on.\n\nA wardrobe built on solid foundations takes the decision out of getting dressed. You already know what works. You already know it fits. You just reach for it.\n\nWe\'d love to know which piece has become your most-reached-for. Tell us in the comments 👇',
    hook: 'If you only remember one thing about building a wardrobe, make it this.', script: '', overlay: '' },
  { title: 'Clothes That Get Real Life',
    caption: 'Clothes that get real life. 🤍\n\nNot the version of your day that looks good in a flat lay. The actual one, where you\'re wrestling a coat on at the door, sitting through a long meeting, doing the school run, squeezing in lunch somewhere between everything else.\n\nThat\'s what every piece here is designed for. Comfortable enough to forget you\'re wearing it, flattering enough that you still feel like yourself at 6pm. Organic cotton jersey that moves with you rather than against you, and holds its shape through all of it.\n\nWe named every piece after a woman in our lives, because these clothes are made for women who actually live in them. Not for a photoshoot. For a Monday.\n\nIf you\'ve been looking for pieces that fit real life as well as your body, our DMs are always open and we love hearing from you. 🫶',
    hook: 'We\'re not a flat-lay brand. Here\'s what we actually make clothes for.', script: 'HOOK: We\'re not a flat-lay brand. Here\'s what we actually make clothes for.\n\nBEAT 1 (0–8s) — The school run, the long meeting, lunch squeezed in between everything else. That\'s the day these pieces are built for. (Sally to camera, relaxed and direct)\n\nBEAT 2 (8–22s) — GOTS-certified organic cotton jersey moves with you rather than against you, and holds its shape so you still feel like yourself at 6pm. (garment detail close-up, fabric in motion)\n\nCTA: Our DMs are always open and we love hearing from you. 🫶', overlay: '' },
  { title: 'Someone in Your Corner',
    caption: 'We are not just here to sell you clothes. 🤍\n\nWe are here to help you work out what actually works for you. Your shape, your lifestyle, your wardrobe gaps. If you are not sure whether something will fit, or you want a second opinion before you buy, just ask us. Our DMs are always open and we love hearing from you.\n\nEvery woman who shops with us deserves to feel confident in what she is buying. Not just on the day it arrives, but on the fortieth wear too. That is what we are here for: not a quick sale, but the right piece for you, chosen properly.\n\nWe answer every message ourselves. There is no chatbot, no auto-reply, no one reading from a script. If you have a question about sizing, fit, fabric, or how to style something, pop us a DM or drop us an email. We will give you a straight answer, every time. 🫶',
    hook: 'When did you last open your wardrobe and actually felt calm?', script: '', overlay: '' },
  { title: 'Why We Made This',
    caption: 'Can I tell you why Ivy exists?\n\nI spent years working in fashion. I knew how clothes were made, what they cost to produce, and what corners were being cut. And still, every morning, I stood in front of my wardrobe and couldn\'t find what I actually needed. A long sleeve T-Shirt that fit well, washed well, and didn\'t look tired after five wears. Something simple. Something I could just reach for.\n\nIt didn\'t exist. Not in the way I wanted it to. So I made it.\n\nEvery piece at Ivy T starts from that same question: what does a woman actually need? Not what\'s trending, not what photographs well for thirty seconds, but what she\'ll reach for on a Tuesday morning when she has a hundred other things to think about. The answer is always the same. Something well made, in a fabric that feels right against her skin, cut to fit how she actually lives.\n\nThat\'s it. That\'s why we\'re here.\n\nSally x',
    hook: 'Nobody talks about how you can spend years inside the fashion industry and still not own a T-shirt worth keeping. So I will.', script: 'HOOK: Nobody talks about how you can spend years inside the fashion industry and still not own a T-shirt worth keeping. So I will.\n\nBEAT 1 (0–10s) — I knew exactly how clothes were made, what corners were being cut, and it still didn\'t help me find something simple that fit well and lasted. (Sally to camera, direct eye contact)\n\nBEAT 2 (10–22s) — So I made Ivy because the question I couldn\'t answer for myself is the one every piece starts from: what does a woman actually reach for on a Tuesday morning when she has a hundred other things to think about? (garment detail close-up, hands holding folded tee)\n\nCLOSE (22–30s) — That\'s it. That\'s why we\'re here. I\'d love to know if that resonates with you. (Sally to camera, soft smile)', overlay: '' },
  { title: 'Good Values, Worn Every Day',
    caption: 'We don\'t make ethical clothing because it\'s a trend. We make it because we can\'t see another way to do it. 🤍\n\nEvery piece starts with GOTS-certified organic cotton, grown without synthetic pesticides, processed using 91% less water and 62% less energy than conventional cotton. Then it goes to our factory in Portugal, a Sedex-approved facility where workers are paid fairly, solar power keeps the lights on, and quality is built in from the first stitch.\n\nSmall batches. No overproduction. No cutting corners to hit a lower price point. Just garments made properly, from fabrics chosen with care, in a place we\'re proud to be associated with.\n\nWe won\'t ever claim to be perfect, but we can tell you that every decision we make starts in the same place: what is the right thing to do here? That question shapes everything from the cotton we source to the wages we pay to the way we pack your order.\n\nGood values don\'t have to stay behind the scenes. They can sit quietly in every seam, wash after wash, wear after wear.\n\nHead to the link in our bio if you\'d like to know more about how we make what we make 🫶',
    hook: 'Everyone says ethical clothing is a compromise. We\'ve never found one.', script: 'HOOK: Everyone says ethical clothing is a compromise. We\'ve never found one. (Sally to camera, direct)\n\nBEAT 1 (0–10s) — Every piece starts with GOTS-certified organic cotton, grown without synthetic pesticides and processed using a fraction of the water conventional cotton needs. (fabric swatch close-up)\n\nBEAT 2 (10–22s) — Then it goes to our Sedex-approved factory in Portugal, where workers are paid fairly and solar power runs the facility, because corners aren\'t something we cut to hit a lower price point. (factory exterior or garment detail shot)\n\nCTA: Head to the link in our bio if you\'d like to know more about how we make what we make. 🫶', overlay: '' },
  { title: 'The Relationships That Shape Us',
    caption: 'Every piece I make is named after a real woman.\n\nNot a trend report. Not a brainstorm session. A real person. A friend, a sister, a daughter, a woman who showed up in my life and left something worth holding on to.\n\nThat\'s where Hannah comes from. And Mabel. And Emma, Claire, Connie, Erin, Maggie, and the rest of them. Each name carries a relationship, a memory, a moment of being properly known.\n\nWhen you reach for one of these pieces in the morning, you\'re not just pulling on a T-Shirt. You\'re wearing something named with real affection, made to show up for you the same way the women behind those names have shown up for me.\n\nFamiliar friends in your wardrobe. That\'s exactly what I set out to make.\n\nLove, Sally x',
    hook: 'Every piece I make is named after a real woman. Here\'s what I mean by that.', script: 'HOOK: Every piece I make is named after a real woman. Here\'s what I mean by that.\n(Sally to camera, warm and direct)\n\nBEAT 1 (0–8s) — Not a trend report, not a brainstorm session. Hannah, Mabel, Emma, Claire, Connie. Each name is a friend, a sister, a woman who showed up in my life and left something worth holding on to.\n(slow pan across folded garments, names visible on labels or tags)\n\nBEAT 2 (8–22s) — So when you reach for one of these pieces in the morning, you\'re wearing something named with real affection, made to show up for you the same way those women have shown up for me.\n(close-up of hands lifting a folded tee, then Sally smiling to camera)\n\nCTA: I\'d love to know which name is yours.\n(Sally, relaxed, to camera)', overlay: '' },
  { title: 'WSG: Easy Mornings With Layla',
    caption: 'Saturday mornings are for slow coffees and zero wardrobe decisions. 🤍\n\nThis week I kept reaching for the Layla Navy Breton T-Shirt. She goes on without a second thought, pairs with everything I already own, and somehow makes even a busy Tuesday morning feel a little more manageable.\n\nThat\'s what I want from my clothes. Not a decision. A reach. The kind of top that does the thinking for you so you don\'t have to.\n\nIf your mornings feel like too much before they\'ve even started, a piece like Layla is worth every penny. Simple, comfortable, flattering, and there every single time you need her.\n\nHave a lovely weekend, love, Sally 😘',
    hook: 'Have you ever stood in front of a full wardrobe and still couldn\'t decide what to put on?', script: '', overlay: '' },
  { title: 'Foundations You Can Rely On',
    caption: 'Every wardrobe needs a foundation. 🤍\n\nNot the pieces you reach for when you\'re trying. The ones you reach for when you\'re not thinking at all. The Audrey Organic Cotton T-Shirt, the Erin 3/4 Sleeve T-Shirt, the Hannah Midweight T-Shirt. Pieces that work quietly, wash beautifully, and show up for you week after week without asking anything in return.\n\nThat\'s what we mean by foundations. Not a trend. Not a capsule you rebuild every season. A small, considered set of pieces that make everything else in your wardrobe easier, because they are dependable in a way that most clothes simply aren\'t.\n\nOur organic cotton jersey holds its shape, its colour, and its softness wash after wash. No bobbly collar after six months. No twist at the seam. No going limp after the third wear. Just the same reliable piece, reach after reach after reach.\n\nIf you\'re building yours, or rebuilding it with intention, our DMs are always open and we love helping you find the right starting point. 🫶',
    hook: 'Nobody talks about the pieces that make every other piece work. So we will.', script: 'HOOK: Nobody talks about the pieces that make every other piece work. So we will.\n\nBEAT 1 (0–10s) — The Audrey, the Erin, the Hannah. Not the pieces you reach for when you\'re trying — the ones you reach for when you\'re not thinking at all. (Sally to camera, three folded tees visible on a surface beside her)\n\nBEAT 2 (10–22s) — Our organic cotton jersey holds its shape, its colour, and its softness wash after wash, because the knit is stable in a way that synthetic blends simply aren\'t. No twist at the seam. No limp collar after six months. Just the same reliable piece, reach after reach. (close-up of fabric texture, then collar detail)\n\nCTA: If you\'re building your foundations, our DMs are always open and we love helping you find the right starting point. 🫶', overlay: '' },
  { title: 'The Audrey Edit — Tease',
    caption: 'Something is coming this month, and if you love Audrey, you\'re going to want to know about it. 🤍\n\nShe has been our most-reached-for long sleeve T-Shirt since the day she arrived, and she is about to get a little bigger. Five new colours are joining the Audrey Edit on the 25th.\n\nWe are not giving everything away just yet, but we will say this: the new shades have been chosen with the same intention as everything else we make. Pieces you will reach for on repeat, in colours that earn their place in your wardrobe and stay there.\n\nComment \'AUDREY\' below and we will make sure you are the first to know when she drops 👇',
    hook: '', script: '', overlay: '' },
  { title: 'Designed Around Real Women',
    caption: 'Every piece we make starts with the same question: does this actually work for real life?\n\nNot for a shoot. Not for one perfect morning. For the school run, the desk, the dinner, the everything-in-between. For the body you have today, not the one you\'re waiting to feel comfortable in.\n\nThat\'s why the fit is thought through properly. Why the fabric moves with you rather than against you. Why there are no fussy details that need babying, no shapes that only work in theory.\n\nAnd it\'s why each piece is named after a real woman. Not a concept, not a mood board. Someone Sally knows, someone who deserves a little something made with her in mind.\n\nWe\'d love to know which piece feels most like it was made for you. Tell us in the comments 👇',
    hook: 'Have you ever worn something that felt like it was made for your actual life?', script: 'HOOK: Have you ever worn something that felt like it was made for your actual life?\n\nBEAT 1 (0–10s) — Every piece we make starts with the same question: does this work for the school run, the desk, the dinner, the everything in between? (Sally to camera, relaxed and direct)\n\nBEAT 2 (10–22s) — The fit moves with you rather than against you, there are no fussy details that need babying, and each piece is named after a real woman Sally knows personally, because that\'s who she\'s designing for. (garment detail close-up, then flat-lay of named pieces)\n\nCTA: We\'d love to know which piece feels most like it was made for you. Tell us in the comments. 👇', overlay: '' },
  { title: 'Always in Your Corner',
    caption: 'We\'re not a faceless website. We\'re here. 🫶\n\nIf you\'re unsure whether a piece will work for your shape, your height, your lifestyle, just ask. Our DMs are always open and we love hearing from you. Email works too. There\'s no question too small and no sizing puzzle we haven\'t seen before.\n\nWe know that buying clothes online, especially pieces you\'re investing in, can feel like a leap of faith. That\'s why we try to make it as easy as possible to get the right thing the first time. Real answers, from real people, quickly.\n\nWe\'re always in your corner. That part doesn\'t change. 🤍',
    hook: 'POV: you\'re about to buy something online and you\'re not quite sure it\'ll work for you.', script: 'HOOK: POV: you\'re about to buy something online and you\'re not quite sure it\'ll work for you.\n\nBEAT 1 (0–10s) — Just ask us. (Sally to camera, warm and direct) We\'re not a faceless website — there\'s a real person here who\'s seen every sizing puzzle going and genuinely loves helping you get it right.\n\nBEAT 2 (10–22s) — Buying pieces you\'re investing in should never feel like a leap of faith. (garment flat-lay, close detail shot) That\'s exactly why we\'re here.\n\nCTA: Get in touch by DM or email — our DMs are always open and we love hearing from you. 🫶', overlay: '' },
  { title: 'What Our Customers See: Heather',
    caption: 'This is what it looks like when the clothes do exactly what they promised 🤍\n\nWe share these messages because they say it better than we ever could. Real women, real wardrobes, real mornings made a little easier.\n\nHeather got in touch to tell us how she has been wearing her pieces, and honestly, this is everything we set out to do. When a garment quietly earns its place in your everyday routine and keeps earning it, wash after wash, season after season, that is the whole point.\n\nOur DMs are always open and we love hearing from you 🫶 If you have been wearing your Ivy pieces and want to share how, we would love to know.\n\nHead to the link in our bio to find your own new favourite.',
    hook: 'We were told to start with a wide range when we launched. Keeping it small and purposeful was the best call we made.', script: '', overlay: '' },
  { title: 'Doing Right, Without the Noise',
    caption: 'We don\'t compete with fast fashion because we don\'t make fast fashion. We are in our own lane. 🤍\n\nEvery piece is produced in small batches, in consciously sourced fabrics, made in a factory we know and trust. We choose quality over quantity, pay fairly, reduce waste, and create garments designed to be worn for years, not weeks.\n\nNo shortcuts. No volume for the sake of it. No detail for the sake of detail.\n\nWe\'d rather make fewer pieces, make them properly, and stand behind every one of them. If that\'s the kind of fashion you\'re looking for, you\'re exactly who we make them for. 💛',
    hook: 'Competing with fast fashion is overrated. There, we said it.', script: 'HOOK: Competing with fast fashion is overrated. There, we said it.\n\nBEAT 1 (0–7s) — We\'re not in that race, because we never entered it. (Sally to camera, direct)\n\nBEAT 2 (7–22s) — Small batches, a factory we know, fabrics consciously sourced. We\'d rather make fewer pieces and make them properly, because shortcuts always show up in the wear. (garment detail close-up, then flat-lay of folded pieces)\n\nCTA: If that\'s the kind of fashion you\'re looking for, you\'re exactly who we make for. (Sally to camera)', overlay: '' },
  { title: 'Built on Real Connections',
    caption: 'Something we never take lightly 🤍\n\nEvery time someone gets in touch, whether it\'s a sizing question, a note to say a parcel arrived, or just to tell us they love what they ordered, we read it. Every single one.\n\nThis brand was built on those conversations. They shaped the fits, the colourways, the way we approach restocks, the way we talk to you. You\'re not a transaction to us. You\'re the reason we make what we make, the way we make it.\n\nOur DMs are always open and we love hearing from you 🫶',
    hook: 'A customer messaged us just to say her parcel arrived. We want to talk about that.', script: 'HOOK: A customer messaged us just to say her parcel arrived. We want to talk about that.\n\nBEAT 1 (0–8s) — We read every single message that comes in, because those conversations are how this brand was built. (Sally to camera, warm and direct)\n\nBEAT 2 (8–20s) — The fits, the colourways, the way we approach restocks, all of it came from you talking to us, and us actually listening. (close-up of phone screen with DM notifications, then cut back to Sally)\n\nCTA: You\'re not a transaction to us. Our DMs are always open and we love hearing from you. 🫶', overlay: '' },
  { title: 'The Audrey Edit — Launch',
    caption: 'Five new colours. The same Audrey you already love. 🤍\n\nAudrey has been our most-worn long sleeve T-Shirt since the day she arrived, and today she gets five new colours to her name. Every one of them made the same way she always has been: GOTS-certified organic cotton jersey, knitted to hold its shape wash after wash, in a fit that works whether you\'re heading out or staying in.\n\nWe produce her in small batches, in our Sedex-approved Portuguese factory where wages are fair and the energy is solar. No shortcuts. No compromises. Just a piece built to be reached for again and again, for years, not seasons.\n\nShe\'s live now. Head to the link in our bio to find your colour 👇',
    hook: 'Five new colours. The same Audrey you already love.', script: 'HOOK: Five new colours. The same Audrey you already love.\n\nBEAT 1 (0–10s) — She\'s our most-reached-for long sleeve, and she\'s made the same way she always has been: GOTS-certified organic cotton jersey, knitted to hold its shape wash after wash. (close-up of fabric texture, Sally to camera)\n\nBEAT 2 (10–22s) — Small batches, solar-powered factory, fair wages. No shortcuts, no compromises. (flat-lay of the five new colourways side by side)\n\nCTA: She\'s live now. Head to the link in our bio to find your colour. 👇', overlay: '' },
  { title: 'WSG: Keep It Simple With Thia',
    caption: 'Sometimes the simplest thing in your wardrobe is the one that does the most work.\n\nThis week I keep coming back to the Thia Black Fine Stripe Midweight T-Shirt. She\'s not loud about it, but she has this quiet way of pulling an outfit together without you having to think too hard. Stripe that reads as a neutral, weight that works through the season change, fit that sits just right without fussing.\n\nI\'ve had her on with Claire, with Kate, with wide-leg trousers, with a blazer thrown over the top. Every combination just works. No deliberating in front of the mirror, no second-guessing. That\'s the whole point, really.\n\nIf your Monday mornings could do with one less decision, she might be your answer.\n\nHave a lovely weekend, love, Sally 😘',
    hook: 'Getting dressed in under five minutes. Here\'s exactly how.', script: '', overlay: '' },
  { title: 'Steady, Reliable, Always There',
    caption: 'Some pieces in your wardrobe earn their place quietly. 🤍\n\nNot the ones you agonise over in the morning. Not the ones saved for a special occasion. The ones already on your body before you have had a chance to think about it.\n\nSteady, reliable, always there. That is what we set out to make when we started Ivy. Not pieces that demand attention, but pieces that simply work, wash after wash, season after season, without asking anything of you in return.\n\nOrganic cotton that holds its shape because of how it is knitted, not because of anything added to it. Colours chosen to sit happily alongside everything else you already own. Fits shaped around how you actually live in your clothes, not how a garment looks on a hanger.\n\nWe hear from customers all the time who say they came back because something just worked. Not because of a sale, not because they needed something new, but because the piece they bought two years ago still looked right, still washed well, still felt good. That is the version of fashion we are interested in making.\n\nWe would love to know which Ivy piece has become your quiet constant. Tell us in the comments. 👇',
    hook: 'The real reason customers come back to Ivy years later — and it isn\'t a sale.', script: 'HOOK: The real reason customers come back to Ivy years later — and it isn\'t a sale.\n\nBEAT 1 (0–10s) — It\'s because the piece they bought two years ago still holds its shape, still washes well, still feels right — because our organic cotton is knitted to hold its structure without anything added to it. (close-up of fabric being gently stretched and released, showing recovery)\n\nBEAT 2 (10–22s) — We choose colours that sit alongside everything you already own, and fits shaped around how you actually live in your clothes — so she\'s already on your body before you\'ve had a chance to think about it. (flat-lay of neutral colourway pieces alongside everyday wardrobe items)\n\nCTA: We\'d love to know which Ivy piece has become your quiet constant — tell us in the comments. 👇', overlay: '' },
  { title: 'Real Women, Real Wardrobes',
    caption: 'Real women. Real wardrobes. Real life. 🤍\n\nThis is what we hear more than almost anything else: women who have spent years buying clothes that looked great on the hanger and felt wrong the moment they put them on. The wrong fit, the wrong fabric, the kind of top that clings where it shouldn\'t and rides up where it shouldn\'t.\n\nThe women who wear Ivy are not looking for a look. They are looking for clothes that work for the life they actually have. The school run and the meeting. The long day and the dinner out. The Monday morning when you just need to get dressed without a second thought.\n\nEvery piece we make is designed with that woman in mind, because she is the reason Ivy exists. Comfortable, flattering, made from GOTS-certified organic cotton that feels as good on your skin as it looks.\n\nIf that sounds like you, we would love to hear how you wear yours. Drop us a comment or pop us a DM, our DMs are always open and we love hearing from you 🫶',
    hook: 'You know that feeling when a top looks perfect on the hanger and feels completely wrong the moment you put it on? We wanted to fix that.', script: 'HOOK: You know that feeling when a top looks perfect on the hanger and feels completely wrong the moment you put it on? We wanted to fix that. (Sally to camera, direct eye contact)\n\nBEAT 1 (0–10s) — Every piece we make is designed for the woman who needs to get dressed without a second thought, because her day is already full enough. (flat-lay of folded garments, unhurried)\n\nBEAT 2 (10–22s) — Comfortable, flattering, GOTS-certified organic cotton that feels as good on your skin as it looks, because fabric that irritates you by midday isn\'t doing its job. (garment-detail close-up, fabric texture)\n\nCTA: We\'d love to hear how you wear yours. Drop us a comment or pop us a DM. 🫶 (Sally to camera, warm smile)', overlay: '' },
  { title: 'The Audrey Edit — Follow-up',
    caption: 'The Audrey Edit has landed, and the colours are already doing the talking. 🤍\n\nFive new shades, all in the same Audrey long sleeve you already know and reach for. Same flattering fit, same GOTS-certified organic cotton jersey, same comfortable weight that moves with you from early morning to later in the day without a second thought.\n\nThis is what a simpler wardrobe looks like in practice. One style you trust, in a colour that quietly makes everything else around it work. Pull her on, and that part of the morning is done.\n\nThe five new colours are live now. Head to the link in our bio to find yours, or pop us a DM if you have any questions about fit or which shade suits you best. Our DMs are always open and we love hearing from you 🫶',
    hook: 'Stop rebuilding your outfit from scratch every morning. Start here instead.', script: '', overlay: '' },
  { title: 'A Friend You Can Count On',
    caption: 'We want to be the kind of brand that feels like a friend who actually knows you. 🤍\n\nNot the kind that pushes you towards something just because it\'s new or on offer. The kind that listens, gives you an honest answer, helps you figure out what actually works for your body and your life, and is still there after the purchase.\n\nThat\'s what Ivy is built around. Every piece is named after a real woman. Every size question, every fit query, every \'I\'m not sure which one is right for me\' message gets a straight, thoughtful answer. Our DMs are always open and we love hearing from you.\n\nIf you\'ve ever felt like shopping for clothes should be easier and more enjoyable than it is, you\'re exactly who we had in mind. 🫶',
    hook: 'Things Ivy customers know that first-time shoppers don\'t.', script: 'HOOK: Things Ivy customers know that first-time shoppers don\'t.\n\nBEAT 1 (0–8s) — Every piece is named after a real woman, and every size question, every "I\'m not sure which one is right for me" message gets a straight, honest answer — because that\'s what a friend does. (Sally to camera, warm and direct)\n\nBEAT 2 (8–22s) — We\'re not here to push you towards something just because it\'s new — we\'re here to help you figure out what works for your body and your life, and to still be here after the purchase. (garment detail close-up, then back to Sally)\n\nCLOSE (22–30s) — That\'s what Ivy is built around. I\'d love to know if that\'s what brought you here too. (Sally to camera, soft smile)', overlay: '' },
  { title: 'Born From a Real Gap',
    caption: 'Ivy started because I couldn\'t find what I needed anywhere else. 🤍\n\nI wasn\'t looking for fast fashion and I wasn\'t looking for something that felt complicated or precious. I just wanted a long sleeve T-shirt that fitted properly, washed well, held its shape and felt good against my skin. I looked everywhere. It didn\'t exist. So I made it.\n\nNot because I spotted a gap in a spreadsheet. Because I was the customer who was frustrated, who had a wardrobe full of things she didn\'t reach for, and who knew exactly what was missing.\n\nEverything at Ivy comes from that same place. Real need, not trends. Pieces designed for how you actually live, in GOTS-certified organic cotton that earns its place in your wardrobe and stays there.\n\nThat\'s still the whole point.\n\nLove, Sally x',
    hook: 'I search every shop for a long sleeve T-shirt that fits, washes well, and holds its shape. Nothing.', script: 'HOOK: I search every shop for a long sleeve T-shirt that fits, washes well, and holds its shape. Nothing.\n\nBEAT 1 (0–10s) — So I made one, in GOTS-certified organic cotton, because I was the frustrated customer with a wardrobe full of things she never reached for. (Sally to camera, direct eye contact)\n\nBEAT 2 (10–22s) — That\'s still where every piece at Ivy starts. Real need, not trends. Designed for how you actually live. (garment-detail close-up, fabric hand)\n\nCLOSE (22–30s) — I\'d love to know if that story sounds familiar to you. (Sally to camera, warm)', overlay: '' },
];
