/**
 * caption-overlap.fixtures.ts — six real captions from Ivy T's July 2026, and the plan rows
 * behind them.
 *
 * VERBATIM, because the whole point of the fixture is the score. A paraphrase would exercise the
 * arithmetic and prove nothing about the threshold, and the threshold is the decision this
 * module exists to make. The published captions are public Instagram posts; the plan captions
 * are Sprigly's own output. Nothing here is a client record — no contact, no commercial term, no
 * private correspondence.
 *
 * Pulled from production on 2026-08-03. Each case is one of the four the operator named, plus the
 * two the chain rule exists to settle:
 *
 *   VERBATIM_1_00        published 15 July — pasted unchanged. Scores 1.00.
 *   NEAR_THRESHOLD       published 13 July — the first day of the regime change. Scores 0.892,
 *                        seven hundredths above the cut, which is what makes it worth pinning.
 *   SELF_WRITTEN         published 5 July  — her own Sunday Style post. Nothing we wrote is near it.
 *   RESHAPED_MATCH       published 23 July — she typed into the row AND asked us to rewrite it.
 *                        Matches the RESHAPE, not the baseline. This is the refinement.
 *   TYPED_OVER_MATCH     published 24 July — same shape, two reshapes deep.
 *   NO_PLAN_ROW          published 3 July  — no plan post for that date at all.
 */

/** 2026-07-15 */
export const VERBATIM_1_00 = {
  date: "2026-07-15",
  published: "I still have a sweatshirt from a high street brand that I have had for years. It is made from 50% cotton, 50% polyester. It has been washed a lot. \n\nGuess what? It’s pilled. Can you see? 👆\n\nAnd the reason is the polyester.\n\nHere is what actually happens. Polyester is a plastic fibre. When you wash a polyester blend, the heat, friction and agitation inside the drum cause those plastic fibres to break down and work their way loose from the fabric structure. They do not disappear. They migrate to the surface of the knit and tangle together into the small, rough bobbles you can feel under your fingers. The more you wash it, the more fibres break free, and the worse the pilling gets. It is not wear and tear. It is the material doing exactly what plastic does under stress.\n\n🌱 Organic cotton fibres are different. They are natural and breathable and hold their position in the knit far better over time. Our Connie sweatshirt fabric is knitted in 100% GOTS-certified organic cotton, so after many washes, the fabric still looks and feels close to how it did on day one.\n\nThe difference is from the softness in the first wear, combined with the longevity from the tenth, the twentieth, the fortieth wear. That is what you are actually paying for.\n\nConnie in Grey Marl restocks this Friday at 6pm 🩶",
  baseline: "",
  live: "SCHEDULED AM\n\nI still have a sweatshirt from a high street brand that I have had for years. It is made from 50% cotton, 50% polyester. It has been washed a lot. \n\nGuess what? It’s pilled. Can you see? 👆\n\nAnd the reason is the polyester.\n\nHere is what actually happens. Polyester is a plastic fibre. When you wash a polyester blend, the heat, friction and agitation inside the drum cause those plastic fibres to break down and work their way loose from the fabric structure. They do not disappear. They migrate to the surface of the knit and tangle together into the small, rough bobbles you can feel under your fingers. The more you wash it, the more fibres break free, and the worse the pilling gets. It is not wear and tear. It is the material doing exactly what plastic does under stress.\n\n🌱 Organic cotton fibres are different. They are natural and breathable and hold their position in the knit far better over time. Our Connie sweatshirt fabric is knitted in 100% GOTS-certified organic cotton, so after many washes, the fabric still looks and feels close to how it did on day one.\n\nThe difference is from the softness in the first wear, combined with the longevity from the tenth, the twentieth, the fortieth wear. That is what you are actually paying for.\n\nConnie in Grey Marl restocks this Friday at 6pm 🩶",
  reshapes: [],
  userTyped: false,
};

/** 2026-07-13 */
export const NEAR_THRESHOLD = {
  date: "2026-07-13",
  published: "What makes a great sweatshirt? \n\nNot all sweatshirts are built the same. Connie, our authentic oversized sweatshirt in GOTS-certified organic cotton, is one of those pieces that earns its place in your wardrobe by being genuinely, quietly brilliant at what it does.\n\nThe weight is right. Heavy enough to feel substantial, light enough that you can wear her year round without overthinking it. The oversized fit skims rather than swamps, and the dropped shoulder sits exactly where it should. The organic cotton jersey is knitted in a way that holds its structure wash after wash, so she looks on the fortieth wear the way she did on the first. 🫶\n\nNo unnecessary detail. No garish logo’s. No contrast stitching there for the sake of it. Just a sweatshirt built to be reached for again and again.\n\nConnie comes back this Friday, in Cobalt 💙, Grey Marl 🩶, and our brand new, beautiful Violet 💜 colour. \n\nComment ‘Connie’ below, 👇 and we’ll sign you up to the waitlist to be the first to hear as soon as they drop 💥",
  baseline: "What makes a great sweatshirt? 🤍\n\nNot all sweatshirts are built the same. Connie, our authentic oversized sweatshirt in GOTS-certified organic cotton, is one of those pieces that earns its place in your wardrobe by being genuinely, quietly brilliant at what it does.\n\nThe weight is right. Heavy enough to feel substantial, light enough that you can wear her from September through to April without overthinking it. The oversized fit skims rather than swamps, and the dropped shoulder sits exactly where it should. The organic cotton jersey is knitted in a way that holds its structure wash after wash, so she looks on the fortieth wear the way she did on the first.\n\nNo unnecessary detail. No logo. No contrast stitching there for the sake of it. Just a sweatshirt built to be reached for again and again.\n\nConnie comes back this Thursday at 7pm, in Cobalt, Grey Marl, and a brand new Violet. We'd love to know which colour you're hoping to get your hands on 👇",
  live: "SCHEDULED AM\nWhat makes a great sweatshirt? 🤍\n\nNot all sweatshirts are built the same. Connie, our authentic oversized sweatshirt in GOTS-certified organic cotton, is one of those pieces that earns its place in your wardrobe by being genuinely, quietly brilliant at what it does.\n\nThe weight is right. Heavy enough to feel substantial, light enough that you can wear her year round without overthinking it. The oversized fit skims rather than swamps, and the dropped shoulder sits exactly where it should. The organic cotton jersey is knitted in a way that holds its structure wash after wash, so she looks on the fortieth wear the way she did on the first.\n\nNo unnecessary detail. No garish logo's. No contrast stitching there for the sake of it. Just a sweatshirt built to be reached for again and again.\n\nConnie comes back this Friday, in Cobalt, Grey Marl, and our brand new, beautiful Violet colour. We'd love to know which colour you're hoping to get your hands on 👇",
  reshapes: [],
  userTyped: false,
};

/** 2026-07-05 */
export const SELF_WRITTEN = {
  date: "2026-07-05",
  published: "S u n d a y  S t y l e 💛💛\n\nSome outfits just make getting dressed that little bit easier.\n​\nWe've put together three effortless looks featuring some of our favourite summer sale pieces—easy combinations that you'll reach for on repeat, whatever your plans.\n\nThe best part? Every piece featured is included in our Feel Good Summer Sale, so there's never been a better time to invest in versatile favourites you'll wear all season long.\n\nShop the looks, mix and match your favourites, and make getting dressed the easiest part of your day.\n\nOutfit 1\n\nAudrey Organic Cotton Navy Breton T-Shirt @ivy_thebrand\nNancy Oversized Organic Cotton Grey Marl Sweatshirt @ivy_thebrand\nShorts - HUSH\nBag - Daylesford\nShoes - Birkenstock\nEarrings - Carrie Elizabeth\n\nOutfit 2\n\nClaire Organic Cotton Dark Olive Skirt @ivy_thebrand\nErin Organic Cotton Navy Breton T-Shirt @ivy_thebrand\nBag - Sezane\nSandals - Penelope Chilvers\nNecklace - Honoura\nEarrings - Oliver Twist Designs\nSunglasses - RayBan\nPerfume - Jo Malone\n\nOutfit 3\n\nHannah Midweight Organic Cotton Lemon T-Shirt @ivy_thebrand\nNancy Oversized Organic Cotton Navy Sweatshirt @ivy_thebrand\nJeans - ME&EM\nShoes - Air & Grace\nEarrings - Monica Vinader\nBag - 46 Stitch\nNail Varnish - Nailberry",
  baseline: '',
  live: '',
  reshapes: [] as string[],
  userTyped: false,
};

/** 2026-07-23 */
export const RESHAPED_MATCH = {
  date: "2026-07-23",
  published: "Why organic cotton is the only choice for sensitive skin 🤍\n\nIf you have ever bought a t-shirt and found your skin is instantly irritated by it, there is a reason. Conventional cotton (not to even mention hormone disrupting, plastic synthetic fibres) is one of the most heavily treated crops in the world. Pesticides, chemical finishes, synthetic dyes. Most of those treatments remain in the finished fabric and garment 😣\n\nGOTS certified organic cotton is grown without synthetic pesticides or fertilisers, and processed without the chemical finishes that cause reactions in sensitive or eczema prone skin. The certification is not a marketing label, it is a rigorous, independently audited standard that covers the entire supply chain from field to finished garment 🤓\n\nOur entire range of sweatshirts, t-shirts, dresses, joggers and shorts are made from GOTS certified organic cotton 🫶\n\nChoosing organic means 91% less water and 62% less energy than conventional cotton. Kinder to your skin and clearer for your conscience 😇\n\nIf you have questions about our fabrics or want to know whether a specific shape is right for you, just pop us a DM - we will be totally transparent and we love hearing from you x",
  baseline: "Why organic cotton is the only choice for sensitive skin. 🤍\n\nIf you have ever bought a T-shirt or sweatshirt and found yourself itching within an hour, or noticed your skin reacting to a fabric you couldn't quite identify, there is usually a reason. Conventional cotton is one of the most heavily treated crops in the world. Pesticides, chemical finishes, synthetic dyes. Most of those treatments remain in the finished fabric.\n\nGOTS-certified organic cotton is grown without synthetic pesticides or fertilisers, and processed without the chemical finishes that cause reactions in sensitive or eczema-prone skin. The certification is not a marketing label, it is a rigorous, independently audited standard that covers the entire supply chain from field to finished garment.\n\nAll of our sweatshirts and T-shirts are made from GOTS-certified organic cotton. That includes Connie, in all three of her colours. It is not a point of difference we added later, it is the reason Ivy exists.\n\nUsing 91% less water and 62% less energy than conventional cotton is what we gain from choosing organic. Kinder skin and a cleaner conscience are what you get.\n\nIf you have questions about our fabrics or want to know whether a specific piece is right for you, just pop us a DM. Our DMs are always open and we love hearing from you 🫶",
  live: "SCHEDULED PM\n\nWhy organic cotton is the only choice for sensitive skin 🤍\n\nIf you have ever bought a t-shirt and found your skin is instantly irritated by it, there is a reason. Conventional cotton (not to even mention hormone disrupting, plastic synthetic fibres) is one of the most heavily treated crops in the world. Pesticides, chemical finishes, synthetic dyes. Most of those treatments remain in the finished fabric and garment 😣\n\nGOTS certified organic cotton is grown without synthetic pesticides or fertilisers, and processed without the chemical finishes that cause reactions in sensitive or eczema prone skin. The certification is not a marketing label, it is a rigorous, independently audited standard that covers the entire supply chain from field to finished garment 🤓\n\nOur entire range of sweatshirts, t-shirts, dresses, joggers and shorts are made from GOTS certified organic cotton 🫶\n\nChoosing organic means 91% less water and 62% less energy than conventional cotton. Kinder to your skin and clearer for your conscience 😇\n\nIf you have questions about our fabrics or want to know whether a specific shape is right for you, just pop us a DM - we will be totally transparent and we love hearing from you x",
  reshapes: ["Why organic cotton is the only choice for sensitive skin 🤍\n\nIf you have ever bought a t-shirt and found your skin is instantly irritated by it, there is a reason. Conventional cotton (not to even mention hormone disrupting, plastic synthetic fibres) is one of the most heavily treated crops in the world. Pesticides, chemical finishes, synthetic dyes. Most of those treatments remain in the finished fabric and garment 😣\n\nGOTS certified organic cotton is grown without synthetic pesticides or fertilisers, and processed without the chemical finishes that cause reactions in sensitive or eczema prone skin. The certification is not a marketing label, it is a rigorous, independently audited standard that covers the entire supply chain from field to finished garment 🤓\n\nOur entire range of sweatshirts, t-shirts, dresses, joggers and shorts are made from GOTS certified organic cotton 🫶\n\nChoosing organic means 91% less water and 62% less energy than conventional cotton. Kinder to your skin and clearer for your conscience.\n\nIf you have questions about our fabrics or want to know whether a specific piece is right for you, just pop us a DM. Our DMs are always open and we love hearing from you 🫶"],
  userTyped: true,
};

/** 2026-07-24 */
export const TYPED_OVER_MATCH = {
  date: "2026-07-24",
  published: "✨ Weekend Style Guide ✨\n\nA day out with the kids in the summer holidays calls for exactly this. Comfort and cool organic cotton ☺️\n\nMaggie in almond, Connie in washed olive tied around my waist, a big denim tote, big sunglasses, and absolutely no fussing about what to wear before we’ve even left the house 💥 \n\nMaggie is generous through the body, long enough to move in comfortably, and the almond shade sits easily with everything else I reach for. Sweatshirt on when the morning is cool, off and around the waist by the time we hit the park 🫶\n\nGOTS-certified organic cotton jersey for both, so comfortable enough to wear all day and still look like you meant it\n\nHappy weekend 😘\n\n[ I am wearing the Maggie Boyfriend T-Shirt in Almond and Connie Sweatshirt in Washed Olive, both in size 12. I am a size 12/14 and 5’8”. Worn with very old Topshop dungarees - I am talking 20+ years old ]",
  baseline: "✨ Weekend Style Guide ✨\n\nI keep coming back to Almond at this time of year. There is something about that warm, barely-there neutral that works with everything I'm reaching for in summer, and Maggie in Almond is one of those pieces I do not think about before I put her on. She is just there, in the rotation, effortlessly.\n\nI've got her on this weekend with my favourite wide-leg linen trousers and flat sandals. Simple, cool, done. She goes just as well over swimwear for the beach, or tucked into a skirt for an evening. One piece, an embarrassing number of ways to wear it.\n\nMaggie is our Boyfriend T-Shirt, cut a little longer and a little more generously than a classic fit, in GOTS-certified organic cotton jersey. She's the T-shirt I recommend to almost anyone who asks where to start with building a wardrobe that actually works.\n\nHappy weekend 😘\n\n[ I am wearing the Maggie Boyfriend T-Shirt in Almond - Ivy T, size M. I am a size 12 and 5'6\" ]",
  live: "✨ Weekend Style Guide ✨\n\nA day out with the kids in the summer holidays calls for exactly this. Comfort and cool organic cotton ☺️\n\nMaggie in almond, Connie in washed olive tied around my waist, a big denim tote, big sunglasses, and absolutely no fussing about what to wear before we’ve even left the house 💥 \n\nMaggie is generous through the body, long enough to move in comfortably, and the almond shade sits easily with everything else I reach for. Sweatshirt on when the morning is cool, off and around the waist by the time we hit the park 🫶\n\nGOTS-certified organic cotton jersey for both, so comfortable enough to wear all day and still look like you meant it\n\nHappy weekend 😘\n\n[ I am wearing the Maggie Boyfriend T-Shirt in Almond and Connie Sweatshirt in Washed Olive, both in size 12. I am a size 12/14 and 5’8”. Worn with very old Topshop dungarees - I am talking 20+ years old ]",
  reshapes: ["✨ Weekend Style Guide ✨\n\nA day out with the kids in the summer holidays calls for exactly this. Maggie in Almond, the Connie Authentic Oversized Sweatshirt in Washed Olive tied around my waist, a big tote, big sunglasses, and absolutely no fussing about what to wear before we've even left the house.\n\nMaggie is generous through the body, long enough to move in comfortably, and that Almond shade goes with practically everything I've already got on. She pairs so well with Connie in Washed Olive, that warm earthy green sits right next to the neutral without a second thought. Sweatshirt on when the morning is cool, off and around the waist by the time we hit the park. Practical without looking like you tried to be practical, which is the whole point.\n\nGOTS-certified organic cotton jersey on both, so comfortable enough to wear all day and still look like you meant it.\n\nHappy weekend 😘\n\n[ I am wearing the Maggie Boyfriend T-Shirt in Almond - Ivy T, and the Connie Authentic Oversized Sweatshirt in Washed Olive - Ivy T. I am a size 12 and 5'6\" ]", "✨ Weekend Style Guide ✨\n\nA day out with the kids in the summer holidays calls for exactly this. Comfort and cool organic cotton.\n\nMaggie in Almond, Connie in Washed Olive tied around my waist, a big denim tote, big sunglasses, and absolutely no fussing about what to wear before we've even left the house.\n\nMaggie is generous through the body, long enough to move in comfortably, and the Almond shade sits easily with everything else I reach for. Sweatshirt on when the morning is cool, off and around the waist by the time we hit the park.\n\nGOTS-certified organic cotton jersey on both, so comfortable enough to wear all day and still look like you meant it.\n\nHappy weekend 😘\n\n[ I am wearing the Maggie Boyfriend T-Shirt in Almond and the Connie Authentic Oversized Sweatshirt in Washed Olive, both in size 12. I am a size 12 and 5'8\". Worn with very old Topshop dungarees - I am talking 20+ years old ]"],
  userTyped: true,
};

/** 2026-07-03 */
export const NO_PLAN_ROW = {
  date: "2026-07-03",
  published: "Maggie, my daughter. The girl who made me a mother AND a business owner.\n\nI started my brand, Ivy, when Maggie was a baby, when I was living in t-shirts and jeans, and needed simple pieces that would hold up to everyday life. I hadn’t found any other tees on the market that fitted the brief: fuss free, quality t-shirts, that helped me feel put together without much thought. So I went about creating a small range of feel good t-shirts myself. Of course I named one of my first tees after Maggie, the girl who started it all 😍\n\n‼️ We’ve just dropped 5 new colours in our OG Maggie tee: purple, dark olive, almond, light sky, and grey marl - all available at ivyt.co.uk right now & while you’re there, take a look at our Feel Good Summer Sale with up to 60% off ‼️\n\n[I’m wearing Maggie in grey marl, size 12, in this video]",
  baseline: '',
  live: '',
  reshapes: [] as string[],
  userTyped: false,
};
